name: PizNation
version: 5.5
main: de.koningjinjin.Main.Main
author: KoningJinjin
commands: 
  heal:
  shop:
  staff:
  help:
  sun:
  tag:
  default:
  setspawn:
  spawn:
  getbow:
  day:
  night:
  a:
  rain: